spring:
  application:
    name: fake-consumer
  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: fake-consumer-shipment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: Shipment:com.github.drnow4u.fakeproducer.Shipment
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.github.drnow4u.fakeproducer.Shipment
        spring.json.use.type.info.headers: "false"

server:
  port: 8081
